  Event: {
    s1: "active" { style.fill: red }
    s2: "done" { style.fill: limegreen }
    s3: "done" { style.fill: limegreen }
    s4: "done" { style.fill: limegreen }
    s5: "done" { style.fill: limegreen }
    s6: "done" { style.fill: limegreen }

    s1 -> s2: "Step 1" {style.font-size: 65} 
    s2 -> s3: "Step 2" {style.font-size: 65} 
    s3 -> s4: "Step 3" {style.font-size: 65} 
    s4 -> s5: "Step 4" {style.font-size: 65} 
    s5 -> s6: "Step 5" {style.font-size: 65} 
  }

  M31: {
    s0: "relevant" { style.fill: limegreen }
    s1: "obsolete" { style.fill: red }
    s2: "obsolete" { style.fill: red }
    s3: "checking" { style.fill: yellow }
    s4: "building" { style.fill: orange }
    s5: "relevant" { style.fill: limegreen }

    s0 -> s1: "Step 1" {style.font-size: 65} 
    s1 -> s2: "Step 2" {style.font-size: 65} 
    s2 -> s3: "Step 3" {style.font-size: 65} 
    s3 -> s4: "Step 4" {style.font-size: 65} 
    s4 -> s5: "Step 5" {style.font-size: 65} 
  }

  M21: {
    s0: "relevant" { style.fill: limegreen }
    s1: "obsolete" { style.fill: limegreen }
    s2: "obsolete" { style.fill: red }
    s3: "checking" { style.fill: yellow }
    s4: "building" { style.fill: orange }
    s5: "relevant" { style.fill: limegreen }

    s0 -> s1: "Step 1" {style.font-size: 65} 
    s1 -> s2: "Step 2" {style.font-size: 65} 
    s2 -> s3: "Step 3" {style.font-size: 65} 
    s3 -> s4: "Step 4" {style.font-size: 65} 
    s4 -> s5: "Step 5" {style.font-size: 65} 
  }

  M11: {
    s0: "relevant" { style.fill: limegreen }
    s1: "relevant" { style.fill: limegreen }
    s2: "relevant" { style.fill: limegreen }
    s3: "checking" { style.fill: yellow }
    s4: "building" { style.fill: orange }
    s5: "relevant" { style.fill: limegreen }

    s0 -> s1: "Step 1" {style.font-size: 65} 
    s1 -> s2: "Step 2" {style.font-size: 65} 
    s2 -> s3: "Step 3" {style.font-size: 65} 
    s3 -> s4: "Step 4" {style.font-size: 65} 
    s4 -> s5: "Step 5" {style.font-size: 65} 
  }

  Request: {
    s0: "idle" { style.fill: lightgray }
    s1: "idle" { style.fill: lightgray }
    s2: "waiting" { style.fill: lightgray }
    s3: "waiting" { style.fill: lightgray }
    s4: "waiting" { style.fill: lightgray }
    s5: "executing" { style.fill: yellow }

    s0 -> s1: "Step 1" {style.font-size: 65} 
    s1 -> s2: "Step 2" {style.font-size: 65} 
    s2 -> s3: "Step 3" {style.font-size: 65} 
    s3 -> s4: "Step 4" {style.font-size: 65} 
    s4 -> s5: "Step 5" {style.font-size: 65} 
  }
  **: {
  style.font-size: 65
}
