CS: "Cloud Service 1" 
Clusters:{
C1
C2
C3
C4
C5
}
Single-board PC:{
S1
S2
S3
S4
S5
}

SS: Sensors and actuators{
    Sa1
    Sa2
    Sa3
    Sa4
}


CS -- Clusters.C1{
  style: {
    stroke-dash: 3
  }
}
CS -- Clusters.C2{
  style: {
    stroke-dash: 3
  }
}
CS -- Clusters.C3{
  style: {
    stroke-dash: 3
  }
}
CS -- Clusters.C4{
  style: {
    stroke-dash: 3
  }
}
CS -- Clusters.C5{
  style: {
    stroke-dash: 3
  }
}

Clusters.C1 -- Single-board PC.S1 {
  style: {
    stroke-dash: 3
  }
}
Clusters.C1 -- Single-board PC.S2{
  style: {
    stroke-dash: 3
  }
}
Clusters.C1 -- Single-board PC.S3{
  style: {
    stroke-dash: 3
  }
}
Clusters.C1 -- Single-board PC.S4{
  style: {
    stroke-dash: 3
  }
}
Clusters.C1 -- Single-board PC.S5{
  style: {
    stroke-dash: 3
  }
}

Single-board PC.S1 -- SS.sa1{
  style: {
    stroke-dash: 3
  }
}
Single-board PC.S1 -- SS.sa2{
  style: {
    stroke-dash: 3
  }
}
Single-board PC.S1 -- SS.sa3{
  style: {
    stroke-dash: 3
  }
}
Single-board PC.S1 -- SS.sa4{
  style: {
    stroke-dash: 3
  }
}
Single-board PC.S1 -- SS.sa5{
  style: {
    stroke-dash: 3
  }
}

**: {
  style.font-size: 65{
  style: {
    stroke-dash: 3
  }
}
}
