version: "3"

services:
  coordinate_publisher:
    build:
      context: coordinate_publisher
      dockerfile: coordinate.Dockerfile
    network_mode: host
    deploy:
      replicas: 3

networks:
  proxy:
    external: true