version: "3"

services:
  coordinate_publisher:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    deploy:
      replicas: 1

  frontend:
    image: kts/my-super-web:latest
    networks:
      - proxy
    volumes:
      - /opt/images:/usr/share/nginx/images
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 3

networks:
  proxy:
    external: true