nQ: 5 # число типов запросов
Ls: 5 # средняя длина вектора
nL: 3 # число уровней моделей
mean_TQ: 10 # среднее время между запросами
mean_TE: 10 # среднее время между событиями
t_ME: 10 # время модернизации модели
t_MS: 100 # время синтеза модели с учетом формирования и выполнения диагностической процедуры
TQ : 20 # время выполнения запроса (среднее), когда модель актуальна
NM: 7 # число уровней дерева
level_NM: 3 # число элементов на каждом уровне
Tch: 1 # время проверки достоверности  моделей